# Generated by Django 5.2 on 2025-05-20 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_categoria_fornecedor_alter_produto_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
