# Generated by Django 5.2 on 2025-05-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
